spring:
  application:
    name: job-portal

  datasource:
    url: jdbc:postgresql://localhost:5432/job-portal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${MY_API_KEY}
      chat:
        options:
          model: gpt-4
server:
  port: 8000